name: 'dq_tools_comparison'
version: '1.0'
config-version: 2

profile: 'dq_tools_comparison'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

